// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGoXmPFNx4hhitplnAvDA38JhNMyhhYug',
    appId: '1:896355694858:web:208f5eed3510b124afa2f3',
    messagingSenderId: '896355694858',
    projectId: 'phoneauth-235d6',
    authDomain: 'phoneauth-235d6.firebaseapp.com',
    storageBucket: 'phoneauth-235d6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCF-pGNv_1CtYlJdLkquqZQJuKzc7EPrFA',
    appId: '1:896355694858:android:fb16cecfd757a617afa2f3',
    messagingSenderId: '896355694858',
    projectId: 'phoneauth-235d6',
    storageBucket: 'phoneauth-235d6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCA0oFPz0Jg3kvvFNzUs3KWF95IeK0Vg6w',
    appId: '1:896355694858:ios:2cc6bfd3be3fd0c3afa2f3',
    messagingSenderId: '896355694858',
    projectId: 'phoneauth-235d6',
    storageBucket: 'phoneauth-235d6.appspot.com',
    iosBundleId: 'com.example.firebaseCrud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCA0oFPz0Jg3kvvFNzUs3KWF95IeK0Vg6w',
    appId: '1:896355694858:ios:2cc6bfd3be3fd0c3afa2f3',
    messagingSenderId: '896355694858',
    projectId: 'phoneauth-235d6',
    storageBucket: 'phoneauth-235d6.appspot.com',
    iosBundleId: 'com.example.firebaseCrud',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGoXmPFNx4hhitplnAvDA38JhNMyhhYug',
    appId: '1:896355694858:web:bf4b9efb582dae77afa2f3',
    messagingSenderId: '896355694858',
    projectId: 'phoneauth-235d6',
    authDomain: 'phoneauth-235d6.firebaseapp.com',
    storageBucket: 'phoneauth-235d6.appspot.com',
  );
}
